nginx:
    image: soajsorg/nginx
    links:
        - contorller:controllerProxy
    ports:
        - "80:80"
contorller:
    image: soajsorg/contorller
    links:
        - mongo:dataProxy
    ports:
        - "4000:4000"
        - "5000:5000"
dashboard:
    image: soajsorg/dashboard
    links:
        - mongo:dataProxy
    ports:
        - "4003:4003"
        - "5003:5003"
urac:
    image: soajsorg/urac
    links:
        - mongo:dataProxy
    ports:
        - "4001:4001"
        - "5001:5001"
oauth:
    image: soajsorg/oauth
    links:
        - mongo:dataProxy
    ports:
        - "4002:4002"
        - "5002:5002"
mongo:
    image: mongo
    command: mongod --noprealloc --smallfiles
    ports:
        - "27017:27017"
    volumes:
        - /data:/data
        - /data/db:/data/db