nginx:
    image: soajs_cloud_prod_nginx
    links:
        - controller01:service_proxy01
        - controller02:service_proxy02
        - controller03:service_proxy03
    ports:
        - "80:80"

controller01:
    image: soajs_cloud_prod_controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - uracoauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000"
        - "5000"
    volumes:
        - $HOME/soajs/log/controller01/:/opt/soajs/log/

controller02:
    image: soajs_cloud_prod_controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - uracoauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000"
        - "5000"

controller03:
    image: soajs_cloud_prod_controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - uracoauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000"
        - "5000"

uracoauth01:
    image: soajs_cloud_prod_urac_oauth
    links:
        - mongo:data_proxy
        - mongo:dataProvision_proxy
    ports:
        - "4001"
        - "4003"
        - "5001"
        - "5003"
    volumes:
        - $HOME/soajs/log/uracoauth01/:/opt/soajs/log/

uracoauth02:
    image: soajs_cloud_prod_urac_oauth
    links:
        - mongo:data_proxy
        - mongo:dataProvision_proxy
    ports:
        - "4001"
        - "4003"
        - "5001"
        - "5003"

uracoauth03:
    image: soajs_cloud_prod_urac_oauth
    links:
        - mongo:data_proxy
        - mongo:dataProvision_proxy
    ports:
        - "4001"
        - "4003"
        - "5001"
        - "5003"

examples01:
    image: soajs_cloud_prod_examples
    links:
        - mongo:data_proxy
        - mongo:dataProvision_proxy
    ports:
        - "4010"
        - "4011"
        - "4012"
        - "4013"
    volumes:
        - $HOME/soajs/log/examples01/:/opt/soajs/log/

mongo:
    image: mongo
    ports:
        - "27017:27017"