nginx:
    build: ./nginx
    links:
        - controller01:service_proxy01
        - controller02:service_proxy02
        - controller03:service_proxy03
    ports:
        - "80:80"

controller01:
    build: ./controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - nodeurac_oauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000:4000"
        - "5000:5000"

controller02:
    build: ./controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - nodeurac_oauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000:4000"
        - "5000:5000"

controller03:
    build: ./controller
    links:
        - uracoauth01:urac_oauth_proxy01
        - uracoauth02:urac_oauth_proxy02
        - nodeurac_oauth03:urac_oauth_proxy03
        - examples01:examples_proxy01
    ports:
        - "4000:4000"
        - "5000:5000"

uracoauth01:
    build: ./urac_oauth
    links:
        - mongo:data_proxy
    ports:
        - "4001:4001"
        - "4003:4003"
        - "5001:5001"
        - "5003:5003"

uracoauth02:
    build: ./urac_oauth
    links:
        - mongo:data_proxy
    ports:
        - "4001:4001"
        - "4003:4003"
        - "5001:5001"
        - "5003:5003"

uracoauth03:
    build: ./urac_oauth
    links:
        - mongo:data_proxy
    ports:
        - "4001:4001"
        - "4003:4003"
        - "5001:5001"
        - "5003:5003"

examples01:
    build: ./examples
    links:
        - mongo:data_proxy
    ports:
        - "4010:4010"
        - "4011:4011"
        - "4012:4012"
        - "4013:4013"

mongo:
    image: mongo
    ports:
        - "27017:27017"